name = "jasper"
version = "1.1.2"

description = "Utilities for parsing and querying JSON data"
licences = ["AGPL-3.0-only"]
repository = { type = "forgejo", host = "git.7cs.dev", user = "lily", repo = "jasper" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
pears = "~> 0.3"

[dev-dependencies]
gleeunit = "~> 1.0"
