name = "jasper"
version = "1.2.0"

description = "Utilities for parsing and querying JSON data"
licences = ["AGPL-3.0-only"]
repository = { type = "github", user = "LilyRose2798", repo = "jasper" }
links = [
  { title = "7Circles Git", href = "https://git.7cs.dev/lily/jasper" },
]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
pears = "~> 0.3"

[dev-dependencies]
gleeunit = "~> 1.0"
