name = "jasper"
version = "2.0.1"

description = "Utilities for parsing and querying JSON data"
licences = ["AGPL-3.0-only"]
repository = { type = "github", user = "LilyRose2798", repo = "jasper" }
links = [
  { title = "7Circles Git", href = "https://git.7cs.dev/lily/jasper" },
]

[dependencies]
gleam_stdlib = ">= 0.62.1 and < 1.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"
